"""
SVD Self-Configuration Training

Uses a STaR-style (Self-Taught Reasoner) training loop:
1. Run episodes where the model configures its own weights via REPL, then solves math
2. Collect successful trajectories (correct answers)
3. Fine-tune the model on those trajectories
4. Repeat

This is the same approach used to train RLM-Qwen3-8B: SFT on successful trajectories
generated by the model interacting with the REPL environment.

Usage:
    python train_svd_agent.py
    python train_svd_agent.py --num_rounds 5 --episodes_per_round 100
    python train_svd_agent.py --model Qwen/Qwen3-1.7B  # if you have more VRAM
"""

import argparse
import json
import random
import time
from pathlib import Path

import torch
from datasets import load_dataset, Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)
from peft import LoraConfig, get_peft_model, TaskType

from svd_repl import SVDManager, REPLEnvironment, episode_to_messages


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_MODEL = "Qwen/Qwen3-0.6B"
DEFAULT_NUM_ROUNDS = 5          # STaR iterations
DEFAULT_EPISODES_PER_ROUND = 50 # episodes to generate per round
DEFAULT_MAX_PROBLEMS = 200      # GSM8K problems to sample from
DEFAULT_MAX_TURNS = 6           # REPL turns per episode
DEFAULT_OUTPUT_DIR = "svd_agent_checkpoints"


# ---------------------------------------------------------------------------
# Episode collection
# ---------------------------------------------------------------------------

def collect_episodes(repl_env, problems, num_episodes, verbose=True):
    """
    Run episodes and collect results.
    Returns (successful_episodes, all_episodes).
    """
    successes = []
    all_episodes = []

    # Sample problems (with replacement if num_episodes > len(problems))
    sampled = [random.choice(problems) for _ in range(num_episodes)]

    for i, prob in enumerate(sampled):
        t0 = time.time()
        episode = repl_env.run_episode(prob["question"], prob["answer"])
        elapsed = time.time() - t0

        all_episodes.append(episode)
        if episode.correct:
            successes.append(episode)

        if verbose:
            status = "CORRECT" if episode.correct else "wrong"
            mods = episode.num_modifications
            turns = len([t for t in episode.turns if t.role == "assistant"])
            print(f"  Episode {i+1}/{num_episodes}: {status} "
                  f"({mods} modifications, {turns} turns, {elapsed:.1f}s) "
                  f"pred={episode.final_answer}")

    return successes, all_episodes


# ---------------------------------------------------------------------------
# SFT on successful trajectories
# ---------------------------------------------------------------------------

def prepare_sft_dataset(episodes, tokenizer, max_length=2048):
    """Convert successful episodes into tokenized SFT training data."""
    samples = []
    for ep in episodes:
        messages = episode_to_messages(ep)
        # Tokenize the full conversation
        text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False,
        )
        tokens = tokenizer(
            text,
            truncation=True,
            max_length=max_length,
            return_tensors="pt",
        )
        input_ids = tokens["input_ids"].squeeze(0)
        # For causal LM training, labels = input_ids
        # (the trainer handles shifting internally)
        samples.append({
            "input_ids": input_ids,
            "labels": input_ids.clone(),
            "attention_mask": torch.ones_like(input_ids),
        })

    return samples


def sft_step(model, tokenizer, episodes, output_dir, round_idx, lr=2e-5):
    """Fine-tune the model on successful episode trajectories."""
    if not episodes:
        print("  No successful episodes to train on, skipping SFT step.")
        return

    print(f"  Preparing SFT data from {len(episodes)} successful episodes...")
    samples = prepare_sft_dataset(episodes, tokenizer)

    # Convert to HF Dataset
    dataset = Dataset.from_dict({
        "input_ids": [s["input_ids"] for s in samples],
        "labels": [s["labels"] for s in samples],
        "attention_mask": [s["attention_mask"] for s in samples],
    })
    dataset.set_format("torch")

    save_dir = f"{output_dir}/round_{round_idx}"

    training_args = TrainingArguments(
        output_dir=save_dir,
        num_train_epochs=2,         # few epochs since data is small
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        learning_rate=lr,
        bf16=True,
        logging_steps=1,
        save_strategy="no",         # we save manually after
        remove_unused_columns=False,
        report_to="none",
    )

    collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        padding=True,
        return_tensors="pt",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        data_collator=collator,
    )

    trainer.train()
    print(f"  SFT complete for round {round_idx}")


# ---------------------------------------------------------------------------
# Baseline evaluation (no SVD modifications)
# ---------------------------------------------------------------------------

def evaluate_baseline(model, tokenizer, problems, num_eval=30):
    """Quick evaluation without any SVD modifications for comparison."""
    correct = 0
    import re
    for prob in problems[:num_eval]:
        messages = [{"role": "user", "content": prob["question"]}]
        prompt = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True,
        )
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        with torch.no_grad():
            out = model.generate(
                **inputs, max_new_tokens=512,
                do_sample=False, temperature=None, top_p=None,
            )
        gen = out[0, inputs["input_ids"].shape[1]:]
        text = tokenizer.decode(gen, skip_special_tokens=True)

        # Extract gold
        gold_match = re.search(r"####\s*(-?[\d,]+)", prob["answer"])
        gold = gold_match.group(1).replace(",", "") if gold_match else None
        # Extract pred
        nums = re.findall(r"-?\d+\.?\d*", text)
        pred = nums[-1] if nums else None

        if gold and pred and gold == pred:
            correct += 1

    return correct, num_eval


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------

def main(args):
    print(f"Loading model: {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model)

    # Disable thinking mode
    if hasattr(tokenizer, "chat_template") and tokenizer.chat_template:
        tokenizer.chat_template = tokenizer.chat_template.replace(
            "enable_thinking=true", "enable_thinking=false"
        )

    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=torch.bfloat16,
        device_map="auto",
    )

    # Apply LoRA for efficient fine-tuning
    if args.use_lora:
        print("Applying LoRA adapter...")
        lora_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=16,
            lora_alpha=32,
            lora_dropout=0.05,
            target_modules=["q_proj", "v_proj", "o_proj",
                            "up_proj", "down_proj", "gate_proj"],
        )
        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()

    # Build SVD manager (operates on the base model weights, not LoRA)
    print("Building SVD manager...")
    base_model = model.base_model.model if args.use_lora else model
    svd_manager = SVDManager(
        base_model,
        max_directions=args.max_directions,
    )

    # Build REPL environment
    repl_env = REPLEnvironment(
        model=model,
        tokenizer=tokenizer,
        svd_manager=svd_manager,
        max_turns=args.max_turns,
    )

    # Load math problems
    print("Loading GSM8K problems...")
    dataset = load_dataset("openai/gsm8k", "main", split="train")
    problems = list(dataset.select(range(min(args.max_problems, len(dataset)))))
    random.shuffle(problems)

    # Separate eval set
    eval_problems = list(dataset.select(range(
        args.max_problems, min(args.max_problems + 50, len(dataset))
    )))

    # Baseline evaluation
    print("\n" + "=" * 60)
    print("BASELINE EVALUATION (no SVD, no REPL)")
    print("=" * 60)
    base_correct, base_total = evaluate_baseline(
        model, tokenizer, eval_problems, num_eval=20
    )
    print(f"Baseline: {base_correct}/{base_total} = {base_correct/base_total:.1%}")

    # Output directory
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # STaR training loop
    all_stats = []
    cumulative_successes = []

    for round_idx in range(args.num_rounds):
        print(f"\n{'=' * 60}")
        print(f"ROUND {round_idx + 1}/{args.num_rounds}")
        print(f"{'=' * 60}")

        # Collect episodes
        print(f"Collecting {args.episodes_per_round} episodes...")
        successes, all_episodes = collect_episodes(
            repl_env, problems, args.episodes_per_round
        )

        success_rate = len(successes) / len(all_episodes) if all_episodes else 0
        print(f"\nRound {round_idx+1} results: "
              f"{len(successes)}/{len(all_episodes)} correct ({success_rate:.1%})")

        # Accumulate successes across rounds for growing training set
        cumulative_successes.extend(successes)

        # Log stats
        stats = {
            "round": round_idx + 1,
            "episodes": len(all_episodes),
            "successes": len(successes),
            "success_rate": success_rate,
            "cumulative_successes": len(cumulative_successes),
        }
        all_stats.append(stats)

        # SFT on successful trajectories
        if successes:
            print(f"\nRunning SFT on {len(successes)} new successful trajectories "
                  f"({len(cumulative_successes)} cumulative)...")
            # Use recent successes + sample from cumulative to avoid forgetting
            train_episodes = successes
            if len(cumulative_successes) > len(successes):
                # Mix in some older successes
                older = [e for e in cumulative_successes if e not in successes]
                sample_size = min(len(older), len(successes))
                train_episodes = successes + random.sample(older, sample_size)

            sft_step(model, tokenizer, train_episodes, str(output_dir), round_idx,
                     lr=args.learning_rate)

        # Save checkpoint
        save_path = output_dir / f"round_{round_idx}"
        save_path.mkdir(parents=True, exist_ok=True)
        model.save_pretrained(str(save_path))
        tokenizer.save_pretrained(str(save_path))
        print(f"Checkpoint saved to {save_path}")

        # Quick eval after training
        print("\nPost-round evaluation...")
        post_correct, post_total = evaluate_baseline(
            model, tokenizer, eval_problems, num_eval=20
        )
        stats["post_eval_accuracy"] = post_correct / post_total
        print(f"Post-round baseline: {post_correct}/{post_total} "
              f"= {post_correct/post_total:.1%}")

    # Final summary
    print(f"\n{'=' * 60}")
    print("TRAINING COMPLETE")
    print(f"{'=' * 60}")
    for s in all_stats:
        post_acc = s.get('post_eval_accuracy', 'N/A')
        if isinstance(post_acc, float):
            post_acc = f"{post_acc:.1%}"
        print(f"  Round {s['round']}: {s['successes']}/{s['episodes']} episodes correct "
              f"({s['success_rate']:.1%}), post-eval={post_acc}")

    # Save stats
    stats_path = output_dir / "training_stats.json"
    with open(stats_path, "w") as f:
        json.dump(all_stats, f, indent=2)
    print(f"\nStats saved to {stats_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(description="SVD Self-Configuration Training")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL)
    parser.add_argument("--num_rounds", type=int, default=DEFAULT_NUM_ROUNDS)
    parser.add_argument("--episodes_per_round", type=int,
                        default=DEFAULT_EPISODES_PER_ROUND)
    parser.add_argument("--max_problems", type=int, default=DEFAULT_MAX_PROBLEMS)
    parser.add_argument("--max_turns", type=int, default=DEFAULT_MAX_TURNS)
    parser.add_argument("--max_directions", type=int, default=20)
    parser.add_argument("--learning_rate", type=float, default=2e-5)
    parser.add_argument("--output_dir", type=str, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--use_lora", action="store_true", default=True)
    parser.add_argument("--no_lora", dest="use_lora", action="store_false")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    main(args)
